trigger:
- master
- develop

variables:
- group: ConqueryConstants

jobs:
############### Frontend Tests
- job: tests_frontend
  displayName: Frontend Tests
  pool:
    vmImage: $(IMAGE)
  steps:
  - task: CacheBeta@0
    inputs:
      key: |
        yarn
        $(Build.SourcesDirectory)/pom.xml
        $(Build.SourcesDirectory)/eva-frontend-resources/pom.xml
        $(Build.SourcesDirectory)/eva-frontend/yarn.lock
      path: $(CACHE_DIR)
  - task: Maven@3
    displayName: frontend tests
    inputs:
      jdkVersion: '1.11'
      goals: package
      options: $(MVN) -pl eva-frontend-resources



############### Backend Tests
- job: tests_backend
  displayName: Backend Tests
  timeoutInMinutes: 15
  pool:
    vmImage: $(IMAGE)
  steps:
  - task: CacheBeta@0
    inputs:
      key: |
        maven
        $(Build.SourcesDirectory)/pom.xml
        $(Build.SourcesDirectory)/eva-backend/pom.xml
        $(Build.SourcesDirectory)/eva-executable/pom.xml
      path: $(CACHE_DIR)

  - task: Maven@3
    displayName: build conquery
    inputs:
      jdkVersion: '1.11'
      goals: install
      options: $(MVN) -T 1C -pl eva-frontend/conquery,eva-frontend/conquery/backend -DskipTests

  - task: Maven@3
    displayName: build root
    inputs:
      jdkVersion: '1.11'
      goals: install
      options: $(MVN) -T 1C -N

  - task: Maven@3
    displayName: unit tests
    inputs:
      jdkVersion: '1.11'
      goals: install
      options: $(MVN) -T 1C -pl eva-backend -DexcludedGroups="INTEGRATION_PROGRAMMATIC, INTEGRATION_JSON"

  - task: Maven@3
    displayName: programmatic integration tests
    inputs:
      jdkVersion: '1.11'
      options: $(MVN) -T 1C -pl eva-backend -Dgroups="INTEGRATION_PROGRAMMATIC"

  - task: Maven@3
    displayName: json integration tests
    inputs:
      jdkVersion: '1.11'
      options: $(MVN) -T 1C -pl eva-backend -Dgroups="INTEGRATION_JSON"

  - task: DeleteFiles@1
    displayName: prepare cache
    inputs:
      sourceFolder: CACHE_DIR/.m2/repository/com/bakdata
      contents: '**'