trigger:
  tags:
    include:
      - '*'
pr: none

variables:
  EXCLUDE_SOURCE_MAPS: true
  MVN_CFG: -B -V -Dmaven.repo.local=$(Build.Repository.LocalPath)/cache/.m2
  YARN_CACHE_FOLDER: $(Build.Repository.LocalPath)/cache/yarn/

pool:
  vmImage: ubuntu-16.04
steps:
- task: Maven@3
  displayName: set version
  inputs:
    jdkVersionOption: '1.11'
    goals: initialize
    options: $(MVN_CFG) -P setEvaVersion
- task: Maven@3
  displayName: build conquery
  inputs:
    jdkVersionOption: '1.11'
    goals: install
    options: $(MVN_CFG) -T 1C -pl eva-frontend/conquery,eva-frontend/conquery/backend -DskipTests
- task: Maven@3
  displayName: build eva
  inputs:
    jdkVersionOption: '1.11'
    goals: package
    options: $(MVN_CFG) -T 1C -DskipTests
- task: GitHubRelease@0
  dispayName: create prerelease
  inputs:
    gitHubConnection: eva
    action: edit
    tagPattern: v\d+\.\d+(\.\d+)?-.*
    tag: $[substring(Build.SourceBranch,11,sub(length(Build.SourceBranch),10))]
    assets: eva-executable/target/eva-executable-*.jar
    isPreRelease: true
    addChangeLog: false