pr: none
trigger:
  tags:
    include:
      - '*'

variables:
- group: ConqueryConstants

pool:
  vmImage: $(IMAGE)
steps:
- bash: |
    echo "trying to extract tag from $(Build.SourceBranch)"
    echo "TAG= ${Build.SourceBranch#refs/tags/}"
    echo "##vso[task.setvariable variable=TAG]${Build.SourceBranch#refs/tags/}"
- task: CacheBeta@0
  inputs:
    key: |
      release
      $(Build.SourcesDirectory)/pom.xml
      $(Build.SourcesDirectory)/frontend-resources/pom.xml
      $(Build.SourcesDirectory)/backend/pom.xml
      $(Build.SourcesDirectory)/executable/pom.xml
      $(Build.SourcesDirectory)/frontend/yarn.lock
    path: $(CACHE_DIR)
- task: Maven@3
  displayName: set version
  inputs:
    jdkVersionOption: '1.11'
    goals: initialize
    options: $(MVN) -P setVersion
- task: Maven@3
  displayName: build conquery
  inputs:
    jdkVersionOption: '1.11'
    options: $(MVN) -T 1C -DskipTests
- task: GitHubRelease@0
  displayName: create prerelease
  inputs:
    gitHubConnection: bot
    action: edit
    tagPattern: v\d+\.\d+(\.\d+)?-.*
    tag: $(TAG)
    assets: executable/target/executable-*.jar
    isPreRelease: true
    addChangeLog: false