name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
branches:
  - 'master'
  - 'develop'
categories:
  - title: '⚙️ Dependencies'
    label: 'dependencies'
template: |
  ## Changes

  $CHANGES


  ### Contributors
  $CONTRIBUTORS