dist: xenial
language: java
os:
  - linux
jdk:
  - openjdk11

before_install: mvn -B -V initialize -P setEvaVersion

stages:
  - name: Prerelease
    if: type = push AND tag IS present AND tag =~ ^v\d+\.\d+(\.\d+)?-.*$
  - name: Release
    if: type = push AND tag IS present AND tag =~ ^v\d+\.\d+(\.\d+)?$

jobs:
  include:
    # ------------------------------
    # Release stages
    # ------------------------------

    - stage: Prerelease
      install:
        - mvn -B -V -T 1C install -pl eva-frontend/conquery,eva-frontend/conquery/backend -DskipTests
        - mvn -B -V -T 1C package -DskipTests
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        file_glob: true
        file: eva-executable/target/eva-executable-*.jar
        skip_cleanup: true
        draft: false
        prerelease: true
        on:
          all_branches: true

    - stage: Release
      install: 
        - mvn -B -V -T 1C install -pl eva-frontend/conquery,eva-frontend/conquery/backend -DskipTests
        - mvn -B -V -T 1C package -DskipTests
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        file_glob: true
        file: eva-executable/target/eva-executable-*.jar
        skip_cleanup: true
        draft: false
        prerelease: false
        on:
          all_branches: true

#remove the installed maven jars before caching
before_cache:
  - rm -f -r $HOME/.m2/repository/com/bakdata/
cache:
  yarn: true
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"
