language: java

env:
  - DOCKER_COMPOSE_VERSION=1.22.0-rc2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  
cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/frontend/node_modules"

script:
  - mvn test -B -DskipDockerTests=false -P reportCoverage

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x frontend/scripts/deploy-npm.sh && sh frontend/scripts/deploy-npm.sh
    on:
      tags: true
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery-dev
    on:
      branch: develop
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery
    on:
      branch: master
