language: java

env:
  - DOCKER_COMPOSE_VERSION=1.18.0

before_script:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/frontend/node_modules"

script:
  - mvn test -B -DskipDockerTests=false -P reportCoverage

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x frontend/scripts/deploy-npm.sh && sh frontend/scripts/deploy-npm.sh
    on:
      tags: true
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery-dev
    on:
      branch: develop
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery
    on:
      branch: master
