trigger:
- master

variables:
  EXCLUDE_SOURCE_MAPS: true
  MVN_CFG: -B -V -Dmaven.repo.local=$(Build.Repository.LocalPath)/cache/.m2
  YARN_CACHE_FOLDER: $(Build.Repository.LocalPath)/cache/yarn/


jobs:
# - job: tests_frontend
#   displayName: Frontend Tests
#   pool:
#     vmImage: ubuntu-16.04
#   steps:

#   - task: Maven@3
#     displayName: frontend tests
#     inputs:
#       jdkVersionOption: '1.11'
#       goals: install
#       options: $(MVN_CFG) -pl eva-frontend-resources

- job: tests_backend
  displayName: Backend Tests
  timeoutInMinutes: 15
  pool:
    vmImage: ubuntu-16.04
  steps:  

  - task: Maven@3
    displayName: build conquery
    inputs:
      jdkVersionOption: '1.11'
      goals: install
      options: $(MVN_CFG) -T 1C -pl eva-frontend/conquery,eva-frontend/conquery/backend -DskipTests

  - task: Maven@3
    displayName: build root
    inputs:
      jdkVersionOption: '1.11'
      goals: install
      options: $(MVN_CFG) -T 1C -N

  - task: Maven@3
    displayName: unit tests
    inputs:
      jdkVersionOption: '1.11'
      goals: install
      options: $(MVN_CFG) -T 1C -pl eva-backend -DexcludedGroups="INTEGRATION_PROGRAMMATIC, INTEGRATION_JSON"

  - task: Maven@3
    displayName: programmatic integration tests
    inputs:
      jdkVersionOption: '1.11'
      goals: test
      options: $(MVN_CFG) -T 1C -pl eva-backend -Dgroups="INTEGRATION_PROGRAMMATIC"

  - task: Maven@3
    displayName: json integration tests
    inputs:
      jdkVersionOption: '1.11'
      goals: test
      options: $(MVN_CFG) -T 1C -pl eva-backend -Dgroups="INTEGRATION_JSON"