name: AutoDoc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package -DskipTests -pl !frontend-resources,!executable
    - name: AutoDoc
      run: cd autodoc && java -jar target/autodoc-0.0.0-SNAPSHOT-jar-with-dependencies.jar
    - name: git status
      run: git status
